### ISSUE TITLE
Your work inspires me a lot, when will the code be released？

### ISSUE THREAD

**Issue by rachel-lyq** [mrkshllr/FewTURE#2]
Your work inspires me a lot,when will the code be released？

**Comment by mrkshllr** [comment]
Hi @rachel-lyq , thanks for reaching out! 
We're currently in the last steps of creating proper training/eval instructions for the Readme (and some minor clean-up) -- so we should be able to release the code incl. instructions how to run/use it within the next 2 weeks.
(If you click the 'watch' button, you should be automatically notified!) 

Let me know if you have any further questions!

**Comment by rachel-lyq** [comment]
Looking forward to your work！

**Comment by mrkshllr** [comment]
Initial release of our code is now available! 
Feel free to raise any issues if you come across anything.
