### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by FushengHao** [mrkshllr/FewTURE#3]
Would you share the pretrained weights?

**Comment by mrkshllr** [comment]
Hi, we are planning to release the pretrained weights soon, so stay tuned! (We'll need to clarify a couple of additional things before we can do so)

**Comment by detectRecog** [comment]
@mrkshllr Happy new year! Don't forget the pre-trained weights. It will be environmentally friendly for us to use pre-trained weights to reproduce the results.

**Comment by mrkshllr** [comment]
@FushengHao @detectRecog 
Self-supervised pretrained weights are now available for both architectures and across all datasets!
-> Please reach out in case you have problems accessing them!
